language: ruby
env:
  global:
    - JRUBY_OPTS=--debug
  matrix:
    - TEST_DIR=api
    - TEST_DIR=sdk
    - TEST_DIR=bridges/opentracing
rvm:
  - 2.4
  - 2.5
  - 2.6
  - jruby
  - truffleruby

install: ( cd api && bundle install --jobs=3 --retry=3 )
script: ( if [ $TEST_DIR=='bridges/opentracing' ]; then gem install opentracing -v 0.5.0; fi && cd $TEST_DIR && rake )
