// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: opencensus/proto/agent/metrics/v1/metrics_service.proto

#ifndef PROTOBUF_INCLUDED_opencensus_2fproto_2fagent_2fmetrics_2fv1_2fmetrics_5fservice_2eproto
#define PROTOBUF_INCLUDED_opencensus_2fproto_2fagent_2fmetrics_2fv1_2fmetrics_5fservice_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3007000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3007001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "opencensus/proto/agent/common/v1/common.pb.h"
#include "opencensus/proto/metrics/v1/metrics.pb.h"
#include "opencensus/proto/resource/v1/resource.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_opencensus_2fproto_2fagent_2fmetrics_2fv1_2fmetrics_5fservice_2eproto

// Internal implementation detail -- do not use these members.
struct TableStruct_opencensus_2fproto_2fagent_2fmetrics_2fv1_2fmetrics_5fservice_2eproto {
  static const ::google::protobuf::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::ParseTable schema[2]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors_opencensus_2fproto_2fagent_2fmetrics_2fv1_2fmetrics_5fservice_2eproto();
namespace opencensus {
namespace proto {
namespace agent {
namespace metrics {
namespace v1 {
class ExportMetricsServiceRequest;
class ExportMetricsServiceRequestDefaultTypeInternal;
extern ExportMetricsServiceRequestDefaultTypeInternal _ExportMetricsServiceRequest_default_instance_;
class ExportMetricsServiceResponse;
class ExportMetricsServiceResponseDefaultTypeInternal;
extern ExportMetricsServiceResponseDefaultTypeInternal _ExportMetricsServiceResponse_default_instance_;
}  // namespace v1
}  // namespace metrics
}  // namespace agent
}  // namespace proto
}  // namespace opencensus
namespace google {
namespace protobuf {
template<> ::opencensus::proto::agent::metrics::v1::ExportMetricsServiceRequest* Arena::CreateMaybeMessage<::opencensus::proto::agent::metrics::v1::ExportMetricsServiceRequest>(Arena*);
template<> ::opencensus::proto::agent::metrics::v1::ExportMetricsServiceResponse* Arena::CreateMaybeMessage<::opencensus::proto::agent::metrics::v1::ExportMetricsServiceResponse>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace opencensus {
namespace proto {
namespace agent {
namespace metrics {
namespace v1 {

// ===================================================================

class ExportMetricsServiceRequest :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:opencensus.proto.agent.metrics.v1.ExportMetricsServiceRequest) */ {
 public:
  ExportMetricsServiceRequest();
  virtual ~ExportMetricsServiceRequest();

  ExportMetricsServiceRequest(const ExportMetricsServiceRequest& from);

  inline ExportMetricsServiceRequest& operator=(const ExportMetricsServiceRequest& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ExportMetricsServiceRequest(ExportMetricsServiceRequest&& from) noexcept
    : ExportMetricsServiceRequest() {
    *this = ::std::move(from);
  }

  inline ExportMetricsServiceRequest& operator=(ExportMetricsServiceRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const ExportMetricsServiceRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ExportMetricsServiceRequest* internal_default_instance() {
    return reinterpret_cast<const ExportMetricsServiceRequest*>(
               &_ExportMetricsServiceRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(ExportMetricsServiceRequest* other);
  friend void swap(ExportMetricsServiceRequest& a, ExportMetricsServiceRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ExportMetricsServiceRequest* New() const final {
    return CreateMaybeMessage<ExportMetricsServiceRequest>(nullptr);
  }

  ExportMetricsServiceRequest* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ExportMetricsServiceRequest>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ExportMetricsServiceRequest& from);
  void MergeFrom(const ExportMetricsServiceRequest& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ExportMetricsServiceRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .opencensus.proto.metrics.v1.Metric metrics = 2;
  int metrics_size() const;
  void clear_metrics();
  static const int kMetricsFieldNumber = 2;
  ::opencensus::proto::metrics::v1::Metric* mutable_metrics(int index);
  ::google::protobuf::RepeatedPtrField< ::opencensus::proto::metrics::v1::Metric >*
      mutable_metrics();
  const ::opencensus::proto::metrics::v1::Metric& metrics(int index) const;
  ::opencensus::proto::metrics::v1::Metric* add_metrics();
  const ::google::protobuf::RepeatedPtrField< ::opencensus::proto::metrics::v1::Metric >&
      metrics() const;

  // .opencensus.proto.agent.common.v1.Node node = 1;
  bool has_node() const;
  void clear_node();
  static const int kNodeFieldNumber = 1;
  const ::opencensus::proto::agent::common::v1::Node& node() const;
  ::opencensus::proto::agent::common::v1::Node* release_node();
  ::opencensus::proto::agent::common::v1::Node* mutable_node();
  void set_allocated_node(::opencensus::proto::agent::common::v1::Node* node);

  // .opencensus.proto.resource.v1.Resource resource = 3;
  bool has_resource() const;
  void clear_resource();
  static const int kResourceFieldNumber = 3;
  const ::opencensus::proto::resource::v1::Resource& resource() const;
  ::opencensus::proto::resource::v1::Resource* release_resource();
  ::opencensus::proto::resource::v1::Resource* mutable_resource();
  void set_allocated_resource(::opencensus::proto::resource::v1::Resource* resource);

  // @@protoc_insertion_point(class_scope:opencensus.proto.agent.metrics.v1.ExportMetricsServiceRequest)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::opencensus::proto::metrics::v1::Metric > metrics_;
  ::opencensus::proto::agent::common::v1::Node* node_;
  ::opencensus::proto::resource::v1::Resource* resource_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_opencensus_2fproto_2fagent_2fmetrics_2fv1_2fmetrics_5fservice_2eproto;
};
// -------------------------------------------------------------------

class ExportMetricsServiceResponse :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:opencensus.proto.agent.metrics.v1.ExportMetricsServiceResponse) */ {
 public:
  ExportMetricsServiceResponse();
  virtual ~ExportMetricsServiceResponse();

  ExportMetricsServiceResponse(const ExportMetricsServiceResponse& from);

  inline ExportMetricsServiceResponse& operator=(const ExportMetricsServiceResponse& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ExportMetricsServiceResponse(ExportMetricsServiceResponse&& from) noexcept
    : ExportMetricsServiceResponse() {
    *this = ::std::move(from);
  }

  inline ExportMetricsServiceResponse& operator=(ExportMetricsServiceResponse&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const ExportMetricsServiceResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ExportMetricsServiceResponse* internal_default_instance() {
    return reinterpret_cast<const ExportMetricsServiceResponse*>(
               &_ExportMetricsServiceResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(ExportMetricsServiceResponse* other);
  friend void swap(ExportMetricsServiceResponse& a, ExportMetricsServiceResponse& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ExportMetricsServiceResponse* New() const final {
    return CreateMaybeMessage<ExportMetricsServiceResponse>(nullptr);
  }

  ExportMetricsServiceResponse* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ExportMetricsServiceResponse>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ExportMetricsServiceResponse& from);
  void MergeFrom(const ExportMetricsServiceResponse& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ExportMetricsServiceResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:opencensus.proto.agent.metrics.v1.ExportMetricsServiceResponse)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_opencensus_2fproto_2fagent_2fmetrics_2fv1_2fmetrics_5fservice_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ExportMetricsServiceRequest

// .opencensus.proto.agent.common.v1.Node node = 1;
inline bool ExportMetricsServiceRequest::has_node() const {
  return this != internal_default_instance() && node_ != nullptr;
}
inline const ::opencensus::proto::agent::common::v1::Node& ExportMetricsServiceRequest::node() const {
  const ::opencensus::proto::agent::common::v1::Node* p = node_;
  // @@protoc_insertion_point(field_get:opencensus.proto.agent.metrics.v1.ExportMetricsServiceRequest.node)
  return p != nullptr ? *p : *reinterpret_cast<const ::opencensus::proto::agent::common::v1::Node*>(
      &::opencensus::proto::agent::common::v1::_Node_default_instance_);
}
inline ::opencensus::proto::agent::common::v1::Node* ExportMetricsServiceRequest::release_node() {
  // @@protoc_insertion_point(field_release:opencensus.proto.agent.metrics.v1.ExportMetricsServiceRequest.node)
  
  ::opencensus::proto::agent::common::v1::Node* temp = node_;
  node_ = nullptr;
  return temp;
}
inline ::opencensus::proto::agent::common::v1::Node* ExportMetricsServiceRequest::mutable_node() {
  
  if (node_ == nullptr) {
    auto* p = CreateMaybeMessage<::opencensus::proto::agent::common::v1::Node>(GetArenaNoVirtual());
    node_ = p;
  }
  // @@protoc_insertion_point(field_mutable:opencensus.proto.agent.metrics.v1.ExportMetricsServiceRequest.node)
  return node_;
}
inline void ExportMetricsServiceRequest::set_allocated_node(::opencensus::proto::agent::common::v1::Node* node) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(node_);
  }
  if (node) {
    ::google::protobuf::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      node = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, node, submessage_arena);
    }
    
  } else {
    
  }
  node_ = node;
  // @@protoc_insertion_point(field_set_allocated:opencensus.proto.agent.metrics.v1.ExportMetricsServiceRequest.node)
}

// repeated .opencensus.proto.metrics.v1.Metric metrics = 2;
inline int ExportMetricsServiceRequest::metrics_size() const {
  return metrics_.size();
}
inline ::opencensus::proto::metrics::v1::Metric* ExportMetricsServiceRequest::mutable_metrics(int index) {
  // @@protoc_insertion_point(field_mutable:opencensus.proto.agent.metrics.v1.ExportMetricsServiceRequest.metrics)
  return metrics_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::opencensus::proto::metrics::v1::Metric >*
ExportMetricsServiceRequest::mutable_metrics() {
  // @@protoc_insertion_point(field_mutable_list:opencensus.proto.agent.metrics.v1.ExportMetricsServiceRequest.metrics)
  return &metrics_;
}
inline const ::opencensus::proto::metrics::v1::Metric& ExportMetricsServiceRequest::metrics(int index) const {
  // @@protoc_insertion_point(field_get:opencensus.proto.agent.metrics.v1.ExportMetricsServiceRequest.metrics)
  return metrics_.Get(index);
}
inline ::opencensus::proto::metrics::v1::Metric* ExportMetricsServiceRequest::add_metrics() {
  // @@protoc_insertion_point(field_add:opencensus.proto.agent.metrics.v1.ExportMetricsServiceRequest.metrics)
  return metrics_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::opencensus::proto::metrics::v1::Metric >&
ExportMetricsServiceRequest::metrics() const {
  // @@protoc_insertion_point(field_list:opencensus.proto.agent.metrics.v1.ExportMetricsServiceRequest.metrics)
  return metrics_;
}

// .opencensus.proto.resource.v1.Resource resource = 3;
inline bool ExportMetricsServiceRequest::has_resource() const {
  return this != internal_default_instance() && resource_ != nullptr;
}
inline const ::opencensus::proto::resource::v1::Resource& ExportMetricsServiceRequest::resource() const {
  const ::opencensus::proto::resource::v1::Resource* p = resource_;
  // @@protoc_insertion_point(field_get:opencensus.proto.agent.metrics.v1.ExportMetricsServiceRequest.resource)
  return p != nullptr ? *p : *reinterpret_cast<const ::opencensus::proto::resource::v1::Resource*>(
      &::opencensus::proto::resource::v1::_Resource_default_instance_);
}
inline ::opencensus::proto::resource::v1::Resource* ExportMetricsServiceRequest::release_resource() {
  // @@protoc_insertion_point(field_release:opencensus.proto.agent.metrics.v1.ExportMetricsServiceRequest.resource)
  
  ::opencensus::proto::resource::v1::Resource* temp = resource_;
  resource_ = nullptr;
  return temp;
}
inline ::opencensus::proto::resource::v1::Resource* ExportMetricsServiceRequest::mutable_resource() {
  
  if (resource_ == nullptr) {
    auto* p = CreateMaybeMessage<::opencensus::proto::resource::v1::Resource>(GetArenaNoVirtual());
    resource_ = p;
  }
  // @@protoc_insertion_point(field_mutable:opencensus.proto.agent.metrics.v1.ExportMetricsServiceRequest.resource)
  return resource_;
}
inline void ExportMetricsServiceRequest::set_allocated_resource(::opencensus::proto::resource::v1::Resource* resource) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(resource_);
  }
  if (resource) {
    ::google::protobuf::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      resource = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, resource, submessage_arena);
    }
    
  } else {
    
  }
  resource_ = resource;
  // @@protoc_insertion_point(field_set_allocated:opencensus.proto.agent.metrics.v1.ExportMetricsServiceRequest.resource)
}

// -------------------------------------------------------------------

// ExportMetricsServiceResponse

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace v1
}  // namespace metrics
}  // namespace agent
}  // namespace proto
}  // namespace opencensus

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // PROTOBUF_INCLUDED_opencensus_2fproto_2fagent_2fmetrics_2fv1_2fmetrics_5fservice_2eproto
