// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: opencensus/proto/agent/metrics/v1/metrics_service.proto

#include "opencensus/proto/agent/metrics/v1/metrics_service.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

extern PROTOBUF_INTERNAL_EXPORT_opencensus_2fproto_2fagent_2fcommon_2fv1_2fcommon_2eproto ::google::protobuf::internal::SCCInfo<4> scc_info_Node_opencensus_2fproto_2fagent_2fcommon_2fv1_2fcommon_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_opencensus_2fproto_2fmetrics_2fv1_2fmetrics_2eproto ::google::protobuf::internal::SCCInfo<3> scc_info_Metric_opencensus_2fproto_2fmetrics_2fv1_2fmetrics_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_opencensus_2fproto_2fresource_2fv1_2fresource_2eproto ::google::protobuf::internal::SCCInfo<1> scc_info_Resource_opencensus_2fproto_2fresource_2fv1_2fresource_2eproto;
namespace opencensus {
namespace proto {
namespace agent {
namespace metrics {
namespace v1 {
class ExportMetricsServiceRequestDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ExportMetricsServiceRequest> _instance;
} _ExportMetricsServiceRequest_default_instance_;
class ExportMetricsServiceResponseDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ExportMetricsServiceResponse> _instance;
} _ExportMetricsServiceResponse_default_instance_;
}  // namespace v1
}  // namespace metrics
}  // namespace agent
}  // namespace proto
}  // namespace opencensus
static void InitDefaultsExportMetricsServiceRequest_opencensus_2fproto_2fagent_2fmetrics_2fv1_2fmetrics_5fservice_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::opencensus::proto::agent::metrics::v1::_ExportMetricsServiceRequest_default_instance_;
    new (ptr) ::opencensus::proto::agent::metrics::v1::ExportMetricsServiceRequest();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::opencensus::proto::agent::metrics::v1::ExportMetricsServiceRequest::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<3> scc_info_ExportMetricsServiceRequest_opencensus_2fproto_2fagent_2fmetrics_2fv1_2fmetrics_5fservice_2eproto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 3, InitDefaultsExportMetricsServiceRequest_opencensus_2fproto_2fagent_2fmetrics_2fv1_2fmetrics_5fservice_2eproto}, {
      &scc_info_Node_opencensus_2fproto_2fagent_2fcommon_2fv1_2fcommon_2eproto.base,
      &scc_info_Metric_opencensus_2fproto_2fmetrics_2fv1_2fmetrics_2eproto.base,
      &scc_info_Resource_opencensus_2fproto_2fresource_2fv1_2fresource_2eproto.base,}};

static void InitDefaultsExportMetricsServiceResponse_opencensus_2fproto_2fagent_2fmetrics_2fv1_2fmetrics_5fservice_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::opencensus::proto::agent::metrics::v1::_ExportMetricsServiceResponse_default_instance_;
    new (ptr) ::opencensus::proto::agent::metrics::v1::ExportMetricsServiceResponse();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::opencensus::proto::agent::metrics::v1::ExportMetricsServiceResponse::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_ExportMetricsServiceResponse_opencensus_2fproto_2fagent_2fmetrics_2fv1_2fmetrics_5fservice_2eproto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsExportMetricsServiceResponse_opencensus_2fproto_2fagent_2fmetrics_2fv1_2fmetrics_5fservice_2eproto}, {}};

void InitDefaults_opencensus_2fproto_2fagent_2fmetrics_2fv1_2fmetrics_5fservice_2eproto() {
  ::google::protobuf::internal::InitSCC(&scc_info_ExportMetricsServiceRequest_opencensus_2fproto_2fagent_2fmetrics_2fv1_2fmetrics_5fservice_2eproto.base);
  ::google::protobuf::internal::InitSCC(&scc_info_ExportMetricsServiceResponse_opencensus_2fproto_2fagent_2fmetrics_2fv1_2fmetrics_5fservice_2eproto.base);
}

::google::protobuf::Metadata file_level_metadata_opencensus_2fproto_2fagent_2fmetrics_2fv1_2fmetrics_5fservice_2eproto[2];
constexpr ::google::protobuf::EnumDescriptor const** file_level_enum_descriptors_opencensus_2fproto_2fagent_2fmetrics_2fv1_2fmetrics_5fservice_2eproto = nullptr;
constexpr ::google::protobuf::ServiceDescriptor const** file_level_service_descriptors_opencensus_2fproto_2fagent_2fmetrics_2fv1_2fmetrics_5fservice_2eproto = nullptr;

const ::google::protobuf::uint32 TableStruct_opencensus_2fproto_2fagent_2fmetrics_2fv1_2fmetrics_5fservice_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::opencensus::proto::agent::metrics::v1::ExportMetricsServiceRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::opencensus::proto::agent::metrics::v1::ExportMetricsServiceRequest, node_),
  PROTOBUF_FIELD_OFFSET(::opencensus::proto::agent::metrics::v1::ExportMetricsServiceRequest, metrics_),
  PROTOBUF_FIELD_OFFSET(::opencensus::proto::agent::metrics::v1::ExportMetricsServiceRequest, resource_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::opencensus::proto::agent::metrics::v1::ExportMetricsServiceResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
};
static const ::google::protobuf::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::opencensus::proto::agent::metrics::v1::ExportMetricsServiceRequest)},
  { 8, -1, sizeof(::opencensus::proto::agent::metrics::v1::ExportMetricsServiceResponse)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::opencensus::proto::agent::metrics::v1::_ExportMetricsServiceRequest_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::opencensus::proto::agent::metrics::v1::_ExportMetricsServiceResponse_default_instance_),
};

::google::protobuf::internal::AssignDescriptorsTable assign_descriptors_table_opencensus_2fproto_2fagent_2fmetrics_2fv1_2fmetrics_5fservice_2eproto = {
  {}, AddDescriptors_opencensus_2fproto_2fagent_2fmetrics_2fv1_2fmetrics_5fservice_2eproto, "opencensus/proto/agent/metrics/v1/metrics_service.proto", schemas,
  file_default_instances, TableStruct_opencensus_2fproto_2fagent_2fmetrics_2fv1_2fmetrics_5fservice_2eproto::offsets,
  file_level_metadata_opencensus_2fproto_2fagent_2fmetrics_2fv1_2fmetrics_5fservice_2eproto, 2, file_level_enum_descriptors_opencensus_2fproto_2fagent_2fmetrics_2fv1_2fmetrics_5fservice_2eproto, file_level_service_descriptors_opencensus_2fproto_2fagent_2fmetrics_2fv1_2fmetrics_5fservice_2eproto,
};

const char descriptor_table_protodef_opencensus_2fproto_2fagent_2fmetrics_2fv1_2fmetrics_5fservice_2eproto[] =
  "\n7opencensus/proto/agent/metrics/v1/metr"
  "ics_service.proto\022!opencensus.proto.agen"
  "t.metrics.v1\032-opencensus/proto/agent/com"
  "mon/v1/common.proto\032)opencensus/proto/me"
  "trics/v1/metrics.proto\032+opencensus/proto"
  "/resource/v1/resource.proto\"\303\001\n\033ExportMe"
  "tricsServiceRequest\0224\n\004node\030\001 \001(\0132&.open"
  "census.proto.agent.common.v1.Node\0224\n\007met"
  "rics\030\002 \003(\0132#.opencensus.proto.metrics.v1"
  ".Metric\0228\n\010resource\030\003 \001(\0132&.opencensus.p"
  "roto.resource.v1.Resource\"\036\n\034ExportMetri"
  "csServiceResponse2\242\001\n\016MetricsService\022\217\001\n"
  "\006Export\022>.opencensus.proto.agent.metrics"
  ".v1.ExportMetricsServiceRequest\032\?.opence"
  "nsus.proto.agent.metrics.v1.ExportMetric"
  "sServiceResponse\"\000(\0010\001B\255\001\n$io.opencensus"
  ".proto.agent.metrics.v1B\023MetricsServiceP"
  "rotoP\001ZJgithub.com/census-instrumentatio"
  "n/opencensus-proto/gen-go/agent/metrics/"
  "v1\352\002!OpenCensus.Proto.Agent.Metrics.V1b\006"
  "proto3"
  ;
::google::protobuf::internal::DescriptorTable descriptor_table_opencensus_2fproto_2fagent_2fmetrics_2fv1_2fmetrics_5fservice_2eproto = {
  false, InitDefaults_opencensus_2fproto_2fagent_2fmetrics_2fv1_2fmetrics_5fservice_2eproto, 
  descriptor_table_protodef_opencensus_2fproto_2fagent_2fmetrics_2fv1_2fmetrics_5fservice_2eproto,
  "opencensus/proto/agent/metrics/v1/metrics_service.proto", &assign_descriptors_table_opencensus_2fproto_2fagent_2fmetrics_2fv1_2fmetrics_5fservice_2eproto, 806,
};

void AddDescriptors_opencensus_2fproto_2fagent_2fmetrics_2fv1_2fmetrics_5fservice_2eproto() {
  static constexpr ::google::protobuf::internal::InitFunc deps[3] =
  {
    ::AddDescriptors_opencensus_2fproto_2fagent_2fcommon_2fv1_2fcommon_2eproto,
    ::AddDescriptors_opencensus_2fproto_2fmetrics_2fv1_2fmetrics_2eproto,
    ::AddDescriptors_opencensus_2fproto_2fresource_2fv1_2fresource_2eproto,
  };
 ::google::protobuf::internal::AddDescriptors(&descriptor_table_opencensus_2fproto_2fagent_2fmetrics_2fv1_2fmetrics_5fservice_2eproto, deps, 3);
}

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_opencensus_2fproto_2fagent_2fmetrics_2fv1_2fmetrics_5fservice_2eproto = []() { AddDescriptors_opencensus_2fproto_2fagent_2fmetrics_2fv1_2fmetrics_5fservice_2eproto(); return true; }();
namespace opencensus {
namespace proto {
namespace agent {
namespace metrics {
namespace v1 {

// ===================================================================

void ExportMetricsServiceRequest::InitAsDefaultInstance() {
  ::opencensus::proto::agent::metrics::v1::_ExportMetricsServiceRequest_default_instance_._instance.get_mutable()->node_ = const_cast< ::opencensus::proto::agent::common::v1::Node*>(
      ::opencensus::proto::agent::common::v1::Node::internal_default_instance());
  ::opencensus::proto::agent::metrics::v1::_ExportMetricsServiceRequest_default_instance_._instance.get_mutable()->resource_ = const_cast< ::opencensus::proto::resource::v1::Resource*>(
      ::opencensus::proto::resource::v1::Resource::internal_default_instance());
}
class ExportMetricsServiceRequest::HasBitSetters {
 public:
  static const ::opencensus::proto::agent::common::v1::Node& node(const ExportMetricsServiceRequest* msg);
  static const ::opencensus::proto::resource::v1::Resource& resource(const ExportMetricsServiceRequest* msg);
};

const ::opencensus::proto::agent::common::v1::Node&
ExportMetricsServiceRequest::HasBitSetters::node(const ExportMetricsServiceRequest* msg) {
  return *msg->node_;
}
const ::opencensus::proto::resource::v1::Resource&
ExportMetricsServiceRequest::HasBitSetters::resource(const ExportMetricsServiceRequest* msg) {
  return *msg->resource_;
}
void ExportMetricsServiceRequest::clear_node() {
  if (GetArenaNoVirtual() == nullptr && node_ != nullptr) {
    delete node_;
  }
  node_ = nullptr;
}
void ExportMetricsServiceRequest::clear_metrics() {
  metrics_.Clear();
}
void ExportMetricsServiceRequest::clear_resource() {
  if (GetArenaNoVirtual() == nullptr && resource_ != nullptr) {
    delete resource_;
  }
  resource_ = nullptr;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ExportMetricsServiceRequest::kNodeFieldNumber;
const int ExportMetricsServiceRequest::kMetricsFieldNumber;
const int ExportMetricsServiceRequest::kResourceFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ExportMetricsServiceRequest::ExportMetricsServiceRequest()
  : ::google::protobuf::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:opencensus.proto.agent.metrics.v1.ExportMetricsServiceRequest)
}
ExportMetricsServiceRequest::ExportMetricsServiceRequest(const ExportMetricsServiceRequest& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(nullptr),
      metrics_(from.metrics_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.has_node()) {
    node_ = new ::opencensus::proto::agent::common::v1::Node(*from.node_);
  } else {
    node_ = nullptr;
  }
  if (from.has_resource()) {
    resource_ = new ::opencensus::proto::resource::v1::Resource(*from.resource_);
  } else {
    resource_ = nullptr;
  }
  // @@protoc_insertion_point(copy_constructor:opencensus.proto.agent.metrics.v1.ExportMetricsServiceRequest)
}

void ExportMetricsServiceRequest::SharedCtor() {
  ::google::protobuf::internal::InitSCC(
      &scc_info_ExportMetricsServiceRequest_opencensus_2fproto_2fagent_2fmetrics_2fv1_2fmetrics_5fservice_2eproto.base);
  ::memset(&node_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&resource_) -
      reinterpret_cast<char*>(&node_)) + sizeof(resource_));
}

ExportMetricsServiceRequest::~ExportMetricsServiceRequest() {
  // @@protoc_insertion_point(destructor:opencensus.proto.agent.metrics.v1.ExportMetricsServiceRequest)
  SharedDtor();
}

void ExportMetricsServiceRequest::SharedDtor() {
  if (this != internal_default_instance()) delete node_;
  if (this != internal_default_instance()) delete resource_;
}

void ExportMetricsServiceRequest::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ExportMetricsServiceRequest& ExportMetricsServiceRequest::default_instance() {
  ::google::protobuf::internal::InitSCC(&::scc_info_ExportMetricsServiceRequest_opencensus_2fproto_2fagent_2fmetrics_2fv1_2fmetrics_5fservice_2eproto.base);
  return *internal_default_instance();
}


void ExportMetricsServiceRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:opencensus.proto.agent.metrics.v1.ExportMetricsServiceRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  metrics_.Clear();
  if (GetArenaNoVirtual() == nullptr && node_ != nullptr) {
    delete node_;
  }
  node_ = nullptr;
  if (GetArenaNoVirtual() == nullptr && resource_ != nullptr) {
    delete resource_;
  }
  resource_ = nullptr;
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* ExportMetricsServiceRequest::_InternalParse(const char* begin, const char* end, void* object,
                  ::google::protobuf::internal::ParseContext* ctx) {
  auto msg = static_cast<ExportMetricsServiceRequest*>(object);
  ::google::protobuf::int32 size; (void)size;
  int depth; (void)depth;
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::ParseFunc parser_till_end; (void)parser_till_end;
  auto ptr = begin;
  while (ptr < end) {
    ptr = ::google::protobuf::io::Parse32(ptr, &tag);
    GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
    switch (tag >> 3) {
      // .opencensus.proto.agent.common.v1.Node node = 1;
      case 1: {
        if (static_cast<::google::protobuf::uint8>(tag) != 10) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        parser_till_end = ::opencensus::proto::agent::common::v1::Node::_InternalParse;
        object = msg->mutable_node();
        if (size > end - ptr) goto len_delim_till_end;
        ptr += size;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ctx->ParseExactRange(
            {parser_till_end, object}, ptr - size, ptr));
        break;
      }
      // repeated .opencensus.proto.metrics.v1.Metric metrics = 2;
      case 2: {
        if (static_cast<::google::protobuf::uint8>(tag) != 18) goto handle_unusual;
        do {
          ptr = ::google::protobuf::io::ReadSize(ptr, &size);
          GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
          parser_till_end = ::opencensus::proto::metrics::v1::Metric::_InternalParse;
          object = msg->add_metrics();
          if (size > end - ptr) goto len_delim_till_end;
          ptr += size;
          GOOGLE_PROTOBUF_PARSER_ASSERT(ctx->ParseExactRange(
              {parser_till_end, object}, ptr - size, ptr));
          if (ptr >= end) break;
        } while ((::google::protobuf::io::UnalignedLoad<::google::protobuf::uint64>(ptr) & 255) == 18 && (ptr += 1));
        break;
      }
      // .opencensus.proto.resource.v1.Resource resource = 3;
      case 3: {
        if (static_cast<::google::protobuf::uint8>(tag) != 26) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        parser_till_end = ::opencensus::proto::resource::v1::Resource::_InternalParse;
        object = msg->mutable_resource();
        if (size > end - ptr) goto len_delim_till_end;
        ptr += size;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ctx->ParseExactRange(
            {parser_till_end, object}, ptr - size, ptr));
        break;
      }
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->EndGroup(tag);
          return ptr;
        }
        auto res = UnknownFieldParse(tag, {_InternalParse, msg},
          ptr, end, msg->_internal_metadata_.mutable_unknown_fields(), ctx);
        ptr = res.first;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr != nullptr);
        if (res.second) return ptr;
      }
    }  // switch
  }  // while
  return ptr;
len_delim_till_end:
  return ctx->StoreAndTailCall(ptr, end, {_InternalParse, msg},
                               {parser_till_end, object}, size);
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool ExportMetricsServiceRequest::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:opencensus.proto.agent.metrics.v1.ExportMetricsServiceRequest)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .opencensus.proto.agent.common.v1.Node node = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (10 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_node()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .opencensus.proto.metrics.v1.Metric metrics = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (18 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_metrics()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .opencensus.proto.resource.v1.Resource resource = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (26 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_resource()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:opencensus.proto.agent.metrics.v1.ExportMetricsServiceRequest)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:opencensus.proto.agent.metrics.v1.ExportMetricsServiceRequest)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void ExportMetricsServiceRequest::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:opencensus.proto.agent.metrics.v1.ExportMetricsServiceRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .opencensus.proto.agent.common.v1.Node node = 1;
  if (this->has_node()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, HasBitSetters::node(this), output);
  }

  // repeated .opencensus.proto.metrics.v1.Metric metrics = 2;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->metrics_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2,
      this->metrics(static_cast<int>(i)),
      output);
  }

  // .opencensus.proto.resource.v1.Resource resource = 3;
  if (this->has_resource()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, HasBitSetters::resource(this), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:opencensus.proto.agent.metrics.v1.ExportMetricsServiceRequest)
}

::google::protobuf::uint8* ExportMetricsServiceRequest::InternalSerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:opencensus.proto.agent.metrics.v1.ExportMetricsServiceRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .opencensus.proto.agent.common.v1.Node node = 1;
  if (this->has_node()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, HasBitSetters::node(this), target);
  }

  // repeated .opencensus.proto.metrics.v1.Metric metrics = 2;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->metrics_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        2, this->metrics(static_cast<int>(i)), target);
  }

  // .opencensus.proto.resource.v1.Resource resource = 3;
  if (this->has_resource()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        3, HasBitSetters::resource(this), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:opencensus.proto.agent.metrics.v1.ExportMetricsServiceRequest)
  return target;
}

size_t ExportMetricsServiceRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:opencensus.proto.agent.metrics.v1.ExportMetricsServiceRequest)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .opencensus.proto.metrics.v1.Metric metrics = 2;
  {
    unsigned int count = static_cast<unsigned int>(this->metrics_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->metrics(static_cast<int>(i)));
    }
  }

  // .opencensus.proto.agent.common.v1.Node node = 1;
  if (this->has_node()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *node_);
  }

  // .opencensus.proto.resource.v1.Resource resource = 3;
  if (this->has_resource()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *resource_);
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ExportMetricsServiceRequest::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:opencensus.proto.agent.metrics.v1.ExportMetricsServiceRequest)
  GOOGLE_DCHECK_NE(&from, this);
  const ExportMetricsServiceRequest* source =
      ::google::protobuf::DynamicCastToGenerated<ExportMetricsServiceRequest>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:opencensus.proto.agent.metrics.v1.ExportMetricsServiceRequest)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:opencensus.proto.agent.metrics.v1.ExportMetricsServiceRequest)
    MergeFrom(*source);
  }
}

void ExportMetricsServiceRequest::MergeFrom(const ExportMetricsServiceRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:opencensus.proto.agent.metrics.v1.ExportMetricsServiceRequest)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  metrics_.MergeFrom(from.metrics_);
  if (from.has_node()) {
    mutable_node()->::opencensus::proto::agent::common::v1::Node::MergeFrom(from.node());
  }
  if (from.has_resource()) {
    mutable_resource()->::opencensus::proto::resource::v1::Resource::MergeFrom(from.resource());
  }
}

void ExportMetricsServiceRequest::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:opencensus.proto.agent.metrics.v1.ExportMetricsServiceRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ExportMetricsServiceRequest::CopyFrom(const ExportMetricsServiceRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:opencensus.proto.agent.metrics.v1.ExportMetricsServiceRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ExportMetricsServiceRequest::IsInitialized() const {
  return true;
}

void ExportMetricsServiceRequest::Swap(ExportMetricsServiceRequest* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ExportMetricsServiceRequest::InternalSwap(ExportMetricsServiceRequest* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  CastToBase(&metrics_)->InternalSwap(CastToBase(&other->metrics_));
  swap(node_, other->node_);
  swap(resource_, other->resource_);
}

::google::protobuf::Metadata ExportMetricsServiceRequest::GetMetadata() const {
  ::google::protobuf::internal::AssignDescriptors(&::assign_descriptors_table_opencensus_2fproto_2fagent_2fmetrics_2fv1_2fmetrics_5fservice_2eproto);
  return ::file_level_metadata_opencensus_2fproto_2fagent_2fmetrics_2fv1_2fmetrics_5fservice_2eproto[kIndexInFileMessages];
}


// ===================================================================

void ExportMetricsServiceResponse::InitAsDefaultInstance() {
}
class ExportMetricsServiceResponse::HasBitSetters {
 public:
};

#if !defined(_MSC_VER) || _MSC_VER >= 1900
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ExportMetricsServiceResponse::ExportMetricsServiceResponse()
  : ::google::protobuf::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:opencensus.proto.agent.metrics.v1.ExportMetricsServiceResponse)
}
ExportMetricsServiceResponse::ExportMetricsServiceResponse(const ExportMetricsServiceResponse& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:opencensus.proto.agent.metrics.v1.ExportMetricsServiceResponse)
}

void ExportMetricsServiceResponse::SharedCtor() {
}

ExportMetricsServiceResponse::~ExportMetricsServiceResponse() {
  // @@protoc_insertion_point(destructor:opencensus.proto.agent.metrics.v1.ExportMetricsServiceResponse)
  SharedDtor();
}

void ExportMetricsServiceResponse::SharedDtor() {
}

void ExportMetricsServiceResponse::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ExportMetricsServiceResponse& ExportMetricsServiceResponse::default_instance() {
  ::google::protobuf::internal::InitSCC(&::scc_info_ExportMetricsServiceResponse_opencensus_2fproto_2fagent_2fmetrics_2fv1_2fmetrics_5fservice_2eproto.base);
  return *internal_default_instance();
}


void ExportMetricsServiceResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:opencensus.proto.agent.metrics.v1.ExportMetricsServiceResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* ExportMetricsServiceResponse::_InternalParse(const char* begin, const char* end, void* object,
                  ::google::protobuf::internal::ParseContext* ctx) {
  auto msg = static_cast<ExportMetricsServiceResponse*>(object);
  ::google::protobuf::int32 size; (void)size;
  int depth; (void)depth;
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::ParseFunc parser_till_end; (void)parser_till_end;
  auto ptr = begin;
  while (ptr < end) {
    ptr = ::google::protobuf::io::Parse32(ptr, &tag);
    GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
    switch (tag >> 3) {
      default: {
        if ((tag & 7) == 4 || tag == 0) {
          ctx->EndGroup(tag);
          return ptr;
        }
        auto res = UnknownFieldParse(tag, {_InternalParse, msg},
          ptr, end, msg->_internal_metadata_.mutable_unknown_fields(), ctx);
        ptr = res.first;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr != nullptr);
        if (res.second) return ptr;
      }
    }  // switch
  }  // while
  return ptr;
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool ExportMetricsServiceResponse::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:opencensus.proto.agent.metrics.v1.ExportMetricsServiceResponse)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
  handle_unusual:
    if (tag == 0) {
      goto success;
    }
    DO_(::google::protobuf::internal::WireFormat::SkipField(
          input, tag, _internal_metadata_.mutable_unknown_fields()));
  }
success:
  // @@protoc_insertion_point(parse_success:opencensus.proto.agent.metrics.v1.ExportMetricsServiceResponse)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:opencensus.proto.agent.metrics.v1.ExportMetricsServiceResponse)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void ExportMetricsServiceResponse::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:opencensus.proto.agent.metrics.v1.ExportMetricsServiceResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:opencensus.proto.agent.metrics.v1.ExportMetricsServiceResponse)
}

::google::protobuf::uint8* ExportMetricsServiceResponse::InternalSerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:opencensus.proto.agent.metrics.v1.ExportMetricsServiceResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:opencensus.proto.agent.metrics.v1.ExportMetricsServiceResponse)
  return target;
}

size_t ExportMetricsServiceResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:opencensus.proto.agent.metrics.v1.ExportMetricsServiceResponse)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ExportMetricsServiceResponse::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:opencensus.proto.agent.metrics.v1.ExportMetricsServiceResponse)
  GOOGLE_DCHECK_NE(&from, this);
  const ExportMetricsServiceResponse* source =
      ::google::protobuf::DynamicCastToGenerated<ExportMetricsServiceResponse>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:opencensus.proto.agent.metrics.v1.ExportMetricsServiceResponse)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:opencensus.proto.agent.metrics.v1.ExportMetricsServiceResponse)
    MergeFrom(*source);
  }
}

void ExportMetricsServiceResponse::MergeFrom(const ExportMetricsServiceResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:opencensus.proto.agent.metrics.v1.ExportMetricsServiceResponse)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

}

void ExportMetricsServiceResponse::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:opencensus.proto.agent.metrics.v1.ExportMetricsServiceResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ExportMetricsServiceResponse::CopyFrom(const ExportMetricsServiceResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:opencensus.proto.agent.metrics.v1.ExportMetricsServiceResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ExportMetricsServiceResponse::IsInitialized() const {
  return true;
}

void ExportMetricsServiceResponse::Swap(ExportMetricsServiceResponse* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ExportMetricsServiceResponse::InternalSwap(ExportMetricsServiceResponse* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata ExportMetricsServiceResponse::GetMetadata() const {
  ::google::protobuf::internal::AssignDescriptors(&::assign_descriptors_table_opencensus_2fproto_2fagent_2fmetrics_2fv1_2fmetrics_5fservice_2eproto);
  return ::file_level_metadata_opencensus_2fproto_2fagent_2fmetrics_2fv1_2fmetrics_5fservice_2eproto[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace v1
}  // namespace metrics
}  // namespace agent
}  // namespace proto
}  // namespace opencensus
namespace google {
namespace protobuf {
template<> PROTOBUF_NOINLINE ::opencensus::proto::agent::metrics::v1::ExportMetricsServiceRequest* Arena::CreateMaybeMessage< ::opencensus::proto::agent::metrics::v1::ExportMetricsServiceRequest >(Arena* arena) {
  return Arena::CreateInternal< ::opencensus::proto::agent::metrics::v1::ExportMetricsServiceRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::opencensus::proto::agent::metrics::v1::ExportMetricsServiceResponse* Arena::CreateMaybeMessage< ::opencensus::proto::agent::metrics::v1::ExportMetricsServiceResponse >(Arena* arena) {
  return Arena::CreateInternal< ::opencensus::proto::agent::metrics::v1::ExportMetricsServiceResponse >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
