// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: opencensus/proto/agent/trace/v1/trace_service.proto

#include "opencensus/proto/agent/trace/v1/trace_service.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

extern PROTOBUF_INTERNAL_EXPORT_opencensus_2fproto_2fagent_2fcommon_2fv1_2fcommon_2eproto ::google::protobuf::internal::SCCInfo<4> scc_info_Node_opencensus_2fproto_2fagent_2fcommon_2fv1_2fcommon_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_opencensus_2fproto_2fresource_2fv1_2fresource_2eproto ::google::protobuf::internal::SCCInfo<1> scc_info_Resource_opencensus_2fproto_2fresource_2fv1_2fresource_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_opencensus_2fproto_2ftrace_2fv1_2ftrace_2eproto ::google::protobuf::internal::SCCInfo<11> scc_info_Span_opencensus_2fproto_2ftrace_2fv1_2ftrace_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_opencensus_2fproto_2ftrace_2fv1_2ftrace_5fconfig_2eproto ::google::protobuf::internal::SCCInfo<3> scc_info_TraceConfig_opencensus_2fproto_2ftrace_2fv1_2ftrace_5fconfig_2eproto;
namespace opencensus {
namespace proto {
namespace agent {
namespace trace {
namespace v1 {
class CurrentLibraryConfigDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<CurrentLibraryConfig> _instance;
} _CurrentLibraryConfig_default_instance_;
class UpdatedLibraryConfigDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<UpdatedLibraryConfig> _instance;
} _UpdatedLibraryConfig_default_instance_;
class ExportTraceServiceRequestDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ExportTraceServiceRequest> _instance;
} _ExportTraceServiceRequest_default_instance_;
class ExportTraceServiceResponseDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ExportTraceServiceResponse> _instance;
} _ExportTraceServiceResponse_default_instance_;
}  // namespace v1
}  // namespace trace
}  // namespace agent
}  // namespace proto
}  // namespace opencensus
static void InitDefaultsCurrentLibraryConfig_opencensus_2fproto_2fagent_2ftrace_2fv1_2ftrace_5fservice_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::opencensus::proto::agent::trace::v1::_CurrentLibraryConfig_default_instance_;
    new (ptr) ::opencensus::proto::agent::trace::v1::CurrentLibraryConfig();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::opencensus::proto::agent::trace::v1::CurrentLibraryConfig::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<2> scc_info_CurrentLibraryConfig_opencensus_2fproto_2fagent_2ftrace_2fv1_2ftrace_5fservice_2eproto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 2, InitDefaultsCurrentLibraryConfig_opencensus_2fproto_2fagent_2ftrace_2fv1_2ftrace_5fservice_2eproto}, {
      &scc_info_Node_opencensus_2fproto_2fagent_2fcommon_2fv1_2fcommon_2eproto.base,
      &scc_info_TraceConfig_opencensus_2fproto_2ftrace_2fv1_2ftrace_5fconfig_2eproto.base,}};

static void InitDefaultsUpdatedLibraryConfig_opencensus_2fproto_2fagent_2ftrace_2fv1_2ftrace_5fservice_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::opencensus::proto::agent::trace::v1::_UpdatedLibraryConfig_default_instance_;
    new (ptr) ::opencensus::proto::agent::trace::v1::UpdatedLibraryConfig();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::opencensus::proto::agent::trace::v1::UpdatedLibraryConfig::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<2> scc_info_UpdatedLibraryConfig_opencensus_2fproto_2fagent_2ftrace_2fv1_2ftrace_5fservice_2eproto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 2, InitDefaultsUpdatedLibraryConfig_opencensus_2fproto_2fagent_2ftrace_2fv1_2ftrace_5fservice_2eproto}, {
      &scc_info_Node_opencensus_2fproto_2fagent_2fcommon_2fv1_2fcommon_2eproto.base,
      &scc_info_TraceConfig_opencensus_2fproto_2ftrace_2fv1_2ftrace_5fconfig_2eproto.base,}};

static void InitDefaultsExportTraceServiceRequest_opencensus_2fproto_2fagent_2ftrace_2fv1_2ftrace_5fservice_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::opencensus::proto::agent::trace::v1::_ExportTraceServiceRequest_default_instance_;
    new (ptr) ::opencensus::proto::agent::trace::v1::ExportTraceServiceRequest();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::opencensus::proto::agent::trace::v1::ExportTraceServiceRequest::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<3> scc_info_ExportTraceServiceRequest_opencensus_2fproto_2fagent_2ftrace_2fv1_2ftrace_5fservice_2eproto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 3, InitDefaultsExportTraceServiceRequest_opencensus_2fproto_2fagent_2ftrace_2fv1_2ftrace_5fservice_2eproto}, {
      &scc_info_Node_opencensus_2fproto_2fagent_2fcommon_2fv1_2fcommon_2eproto.base,
      &scc_info_Span_opencensus_2fproto_2ftrace_2fv1_2ftrace_2eproto.base,
      &scc_info_Resource_opencensus_2fproto_2fresource_2fv1_2fresource_2eproto.base,}};

static void InitDefaultsExportTraceServiceResponse_opencensus_2fproto_2fagent_2ftrace_2fv1_2ftrace_5fservice_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::opencensus::proto::agent::trace::v1::_ExportTraceServiceResponse_default_instance_;
    new (ptr) ::opencensus::proto::agent::trace::v1::ExportTraceServiceResponse();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::opencensus::proto::agent::trace::v1::ExportTraceServiceResponse::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_ExportTraceServiceResponse_opencensus_2fproto_2fagent_2ftrace_2fv1_2ftrace_5fservice_2eproto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsExportTraceServiceResponse_opencensus_2fproto_2fagent_2ftrace_2fv1_2ftrace_5fservice_2eproto}, {}};

void InitDefaults_opencensus_2fproto_2fagent_2ftrace_2fv1_2ftrace_5fservice_2eproto() {
  ::google::protobuf::internal::InitSCC(&scc_info_CurrentLibraryConfig_opencensus_2fproto_2fagent_2ftrace_2fv1_2ftrace_5fservice_2eproto.base);
  ::google::protobuf::internal::InitSCC(&scc_info_UpdatedLibraryConfig_opencensus_2fproto_2fagent_2ftrace_2fv1_2ftrace_5fservice_2eproto.base);
  ::google::protobuf::internal::InitSCC(&scc_info_ExportTraceServiceRequest_opencensus_2fproto_2fagent_2ftrace_2fv1_2ftrace_5fservice_2eproto.base);
  ::google::protobuf::internal::InitSCC(&scc_info_ExportTraceServiceResponse_opencensus_2fproto_2fagent_2ftrace_2fv1_2ftrace_5fservice_2eproto.base);
}

::google::protobuf::Metadata file_level_metadata_opencensus_2fproto_2fagent_2ftrace_2fv1_2ftrace_5fservice_2eproto[4];
constexpr ::google::protobuf::EnumDescriptor const** file_level_enum_descriptors_opencensus_2fproto_2fagent_2ftrace_2fv1_2ftrace_5fservice_2eproto = nullptr;
constexpr ::google::protobuf::ServiceDescriptor const** file_level_service_descriptors_opencensus_2fproto_2fagent_2ftrace_2fv1_2ftrace_5fservice_2eproto = nullptr;

const ::google::protobuf::uint32 TableStruct_opencensus_2fproto_2fagent_2ftrace_2fv1_2ftrace_5fservice_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::opencensus::proto::agent::trace::v1::CurrentLibraryConfig, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::opencensus::proto::agent::trace::v1::CurrentLibraryConfig, node_),
  PROTOBUF_FIELD_OFFSET(::opencensus::proto::agent::trace::v1::CurrentLibraryConfig, config_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::opencensus::proto::agent::trace::v1::UpdatedLibraryConfig, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::opencensus::proto::agent::trace::v1::UpdatedLibraryConfig, node_),
  PROTOBUF_FIELD_OFFSET(::opencensus::proto::agent::trace::v1::UpdatedLibraryConfig, config_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::opencensus::proto::agent::trace::v1::ExportTraceServiceRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::opencensus::proto::agent::trace::v1::ExportTraceServiceRequest, node_),
  PROTOBUF_FIELD_OFFSET(::opencensus::proto::agent::trace::v1::ExportTraceServiceRequest, spans_),
  PROTOBUF_FIELD_OFFSET(::opencensus::proto::agent::trace::v1::ExportTraceServiceRequest, resource_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::opencensus::proto::agent::trace::v1::ExportTraceServiceResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
};
static const ::google::protobuf::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::opencensus::proto::agent::trace::v1::CurrentLibraryConfig)},
  { 7, -1, sizeof(::opencensus::proto::agent::trace::v1::UpdatedLibraryConfig)},
  { 14, -1, sizeof(::opencensus::proto::agent::trace::v1::ExportTraceServiceRequest)},
  { 22, -1, sizeof(::opencensus::proto::agent::trace::v1::ExportTraceServiceResponse)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::opencensus::proto::agent::trace::v1::_CurrentLibraryConfig_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::opencensus::proto::agent::trace::v1::_UpdatedLibraryConfig_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::opencensus::proto::agent::trace::v1::_ExportTraceServiceRequest_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::opencensus::proto::agent::trace::v1::_ExportTraceServiceResponse_default_instance_),
};

::google::protobuf::internal::AssignDescriptorsTable assign_descriptors_table_opencensus_2fproto_2fagent_2ftrace_2fv1_2ftrace_5fservice_2eproto = {
  {}, AddDescriptors_opencensus_2fproto_2fagent_2ftrace_2fv1_2ftrace_5fservice_2eproto, "opencensus/proto/agent/trace/v1/trace_service.proto", schemas,
  file_default_instances, TableStruct_opencensus_2fproto_2fagent_2ftrace_2fv1_2ftrace_5fservice_2eproto::offsets,
  file_level_metadata_opencensus_2fproto_2fagent_2ftrace_2fv1_2ftrace_5fservice_2eproto, 4, file_level_enum_descriptors_opencensus_2fproto_2fagent_2ftrace_2fv1_2ftrace_5fservice_2eproto, file_level_service_descriptors_opencensus_2fproto_2fagent_2ftrace_2fv1_2ftrace_5fservice_2eproto,
};

const char descriptor_table_protodef_opencensus_2fproto_2fagent_2ftrace_2fv1_2ftrace_5fservice_2eproto[] =
  "\n3opencensus/proto/agent/trace/v1/trace_"
  "service.proto\022\037opencensus.proto.agent.tr"
  "ace.v1\032-opencensus/proto/agent/common/v1"
  "/common.proto\032+opencensus/proto/resource"
  "/v1/resource.proto\032%opencensus/proto/tra"
  "ce/v1/trace.proto\032,opencensus/proto/trac"
  "e/v1/trace_config.proto\"\204\001\n\024CurrentLibra"
  "ryConfig\0224\n\004node\030\001 \001(\0132&.opencensus.prot"
  "o.agent.common.v1.Node\0226\n\006config\030\002 \001(\0132&"
  ".opencensus.proto.trace.v1.TraceConfig\"\204"
  "\001\n\024UpdatedLibraryConfig\0224\n\004node\030\001 \001(\0132&."
  "opencensus.proto.agent.common.v1.Node\0226\n"
  "\006config\030\002 \001(\0132&.opencensus.proto.trace.v"
  "1.TraceConfig\"\273\001\n\031ExportTraceServiceRequ"
  "est\0224\n\004node\030\001 \001(\0132&.opencensus.proto.age"
  "nt.common.v1.Node\022.\n\005spans\030\002 \003(\0132\037.openc"
  "ensus.proto.trace.v1.Span\0228\n\010resource\030\003 "
  "\001(\0132&.opencensus.proto.resource.v1.Resou"
  "rce\"\034\n\032ExportTraceServiceResponse2\226\002\n\014Tr"
  "aceService\022|\n\006Config\0225.opencensus.proto."
  "agent.trace.v1.CurrentLibraryConfig\0325.op"
  "encensus.proto.agent.trace.v1.UpdatedLib"
  "raryConfig\"\000(\0010\001\022\207\001\n\006Export\022:.opencensus"
  ".proto.agent.trace.v1.ExportTraceService"
  "Request\032;.opencensus.proto.agent.trace.v"
  "1.ExportTraceServiceResponse\"\000(\0010\001B\245\001\n\"i"
  "o.opencensus.proto.agent.trace.v1B\021Trace"
  "ServiceProtoP\001ZHgithub.com/census-instru"
  "mentation/opencensus-proto/gen-go/agent/"
  "trace/v1\352\002\037OpenCensus.Proto.Agent.Trace."
  "V1b\006proto3"
  ;
::google::protobuf::internal::DescriptorTable descriptor_table_opencensus_2fproto_2fagent_2ftrace_2fv1_2ftrace_5fservice_2eproto = {
  false, InitDefaults_opencensus_2fproto_2fagent_2ftrace_2fv1_2ftrace_5fservice_2eproto, 
  descriptor_table_protodef_opencensus_2fproto_2fagent_2ftrace_2fv1_2ftrace_5fservice_2eproto,
  "opencensus/proto/agent/trace/v1/trace_service.proto", &assign_descriptors_table_opencensus_2fproto_2fagent_2ftrace_2fv1_2ftrace_5fservice_2eproto, 1210,
};

void AddDescriptors_opencensus_2fproto_2fagent_2ftrace_2fv1_2ftrace_5fservice_2eproto() {
  static constexpr ::google::protobuf::internal::InitFunc deps[4] =
  {
    ::AddDescriptors_opencensus_2fproto_2fagent_2fcommon_2fv1_2fcommon_2eproto,
    ::AddDescriptors_opencensus_2fproto_2fresource_2fv1_2fresource_2eproto,
    ::AddDescriptors_opencensus_2fproto_2ftrace_2fv1_2ftrace_2eproto,
    ::AddDescriptors_opencensus_2fproto_2ftrace_2fv1_2ftrace_5fconfig_2eproto,
  };
 ::google::protobuf::internal::AddDescriptors(&descriptor_table_opencensus_2fproto_2fagent_2ftrace_2fv1_2ftrace_5fservice_2eproto, deps, 4);
}

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_opencensus_2fproto_2fagent_2ftrace_2fv1_2ftrace_5fservice_2eproto = []() { AddDescriptors_opencensus_2fproto_2fagent_2ftrace_2fv1_2ftrace_5fservice_2eproto(); return true; }();
namespace opencensus {
namespace proto {
namespace agent {
namespace trace {
namespace v1 {

// ===================================================================

void CurrentLibraryConfig::InitAsDefaultInstance() {
  ::opencensus::proto::agent::trace::v1::_CurrentLibraryConfig_default_instance_._instance.get_mutable()->node_ = const_cast< ::opencensus::proto::agent::common::v1::Node*>(
      ::opencensus::proto::agent::common::v1::Node::internal_default_instance());
  ::opencensus::proto::agent::trace::v1::_CurrentLibraryConfig_default_instance_._instance.get_mutable()->config_ = const_cast< ::opencensus::proto::trace::v1::TraceConfig*>(
      ::opencensus::proto::trace::v1::TraceConfig::internal_default_instance());
}
class CurrentLibraryConfig::HasBitSetters {
 public:
  static const ::opencensus::proto::agent::common::v1::Node& node(const CurrentLibraryConfig* msg);
  static const ::opencensus::proto::trace::v1::TraceConfig& config(const CurrentLibraryConfig* msg);
};

const ::opencensus::proto::agent::common::v1::Node&
CurrentLibraryConfig::HasBitSetters::node(const CurrentLibraryConfig* msg) {
  return *msg->node_;
}
const ::opencensus::proto::trace::v1::TraceConfig&
CurrentLibraryConfig::HasBitSetters::config(const CurrentLibraryConfig* msg) {
  return *msg->config_;
}
void CurrentLibraryConfig::clear_node() {
  if (GetArenaNoVirtual() == nullptr && node_ != nullptr) {
    delete node_;
  }
  node_ = nullptr;
}
void CurrentLibraryConfig::clear_config() {
  if (GetArenaNoVirtual() == nullptr && config_ != nullptr) {
    delete config_;
  }
  config_ = nullptr;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int CurrentLibraryConfig::kNodeFieldNumber;
const int CurrentLibraryConfig::kConfigFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

CurrentLibraryConfig::CurrentLibraryConfig()
  : ::google::protobuf::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:opencensus.proto.agent.trace.v1.CurrentLibraryConfig)
}
CurrentLibraryConfig::CurrentLibraryConfig(const CurrentLibraryConfig& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.has_node()) {
    node_ = new ::opencensus::proto::agent::common::v1::Node(*from.node_);
  } else {
    node_ = nullptr;
  }
  if (from.has_config()) {
    config_ = new ::opencensus::proto::trace::v1::TraceConfig(*from.config_);
  } else {
    config_ = nullptr;
  }
  // @@protoc_insertion_point(copy_constructor:opencensus.proto.agent.trace.v1.CurrentLibraryConfig)
}

void CurrentLibraryConfig::SharedCtor() {
  ::google::protobuf::internal::InitSCC(
      &scc_info_CurrentLibraryConfig_opencensus_2fproto_2fagent_2ftrace_2fv1_2ftrace_5fservice_2eproto.base);
  ::memset(&node_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&config_) -
      reinterpret_cast<char*>(&node_)) + sizeof(config_));
}

CurrentLibraryConfig::~CurrentLibraryConfig() {
  // @@protoc_insertion_point(destructor:opencensus.proto.agent.trace.v1.CurrentLibraryConfig)
  SharedDtor();
}

void CurrentLibraryConfig::SharedDtor() {
  if (this != internal_default_instance()) delete node_;
  if (this != internal_default_instance()) delete config_;
}

void CurrentLibraryConfig::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const CurrentLibraryConfig& CurrentLibraryConfig::default_instance() {
  ::google::protobuf::internal::InitSCC(&::scc_info_CurrentLibraryConfig_opencensus_2fproto_2fagent_2ftrace_2fv1_2ftrace_5fservice_2eproto.base);
  return *internal_default_instance();
}


void CurrentLibraryConfig::Clear() {
// @@protoc_insertion_point(message_clear_start:opencensus.proto.agent.trace.v1.CurrentLibraryConfig)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaNoVirtual() == nullptr && node_ != nullptr) {
    delete node_;
  }
  node_ = nullptr;
  if (GetArenaNoVirtual() == nullptr && config_ != nullptr) {
    delete config_;
  }
  config_ = nullptr;
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* CurrentLibraryConfig::_InternalParse(const char* begin, const char* end, void* object,
                  ::google::protobuf::internal::ParseContext* ctx) {
  auto msg = static_cast<CurrentLibraryConfig*>(object);
  ::google::protobuf::int32 size; (void)size;
  int depth; (void)depth;
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::ParseFunc parser_till_end; (void)parser_till_end;
  auto ptr = begin;
  while (ptr < end) {
    ptr = ::google::protobuf::io::Parse32(ptr, &tag);
    GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
    switch (tag >> 3) {
      // .opencensus.proto.agent.common.v1.Node node = 1;
      case 1: {
        if (static_cast<::google::protobuf::uint8>(tag) != 10) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        parser_till_end = ::opencensus::proto::agent::common::v1::Node::_InternalParse;
        object = msg->mutable_node();
        if (size > end - ptr) goto len_delim_till_end;
        ptr += size;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ctx->ParseExactRange(
            {parser_till_end, object}, ptr - size, ptr));
        break;
      }
      // .opencensus.proto.trace.v1.TraceConfig config = 2;
      case 2: {
        if (static_cast<::google::protobuf::uint8>(tag) != 18) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        parser_till_end = ::opencensus::proto::trace::v1::TraceConfig::_InternalParse;
        object = msg->mutable_config();
        if (size > end - ptr) goto len_delim_till_end;
        ptr += size;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ctx->ParseExactRange(
            {parser_till_end, object}, ptr - size, ptr));
        break;
      }
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->EndGroup(tag);
          return ptr;
        }
        auto res = UnknownFieldParse(tag, {_InternalParse, msg},
          ptr, end, msg->_internal_metadata_.mutable_unknown_fields(), ctx);
        ptr = res.first;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr != nullptr);
        if (res.second) return ptr;
      }
    }  // switch
  }  // while
  return ptr;
len_delim_till_end:
  return ctx->StoreAndTailCall(ptr, end, {_InternalParse, msg},
                               {parser_till_end, object}, size);
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool CurrentLibraryConfig::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:opencensus.proto.agent.trace.v1.CurrentLibraryConfig)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .opencensus.proto.agent.common.v1.Node node = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (10 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_node()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .opencensus.proto.trace.v1.TraceConfig config = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (18 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_config()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:opencensus.proto.agent.trace.v1.CurrentLibraryConfig)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:opencensus.proto.agent.trace.v1.CurrentLibraryConfig)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void CurrentLibraryConfig::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:opencensus.proto.agent.trace.v1.CurrentLibraryConfig)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .opencensus.proto.agent.common.v1.Node node = 1;
  if (this->has_node()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, HasBitSetters::node(this), output);
  }

  // .opencensus.proto.trace.v1.TraceConfig config = 2;
  if (this->has_config()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, HasBitSetters::config(this), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:opencensus.proto.agent.trace.v1.CurrentLibraryConfig)
}

::google::protobuf::uint8* CurrentLibraryConfig::InternalSerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:opencensus.proto.agent.trace.v1.CurrentLibraryConfig)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .opencensus.proto.agent.common.v1.Node node = 1;
  if (this->has_node()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, HasBitSetters::node(this), target);
  }

  // .opencensus.proto.trace.v1.TraceConfig config = 2;
  if (this->has_config()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        2, HasBitSetters::config(this), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:opencensus.proto.agent.trace.v1.CurrentLibraryConfig)
  return target;
}

size_t CurrentLibraryConfig::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:opencensus.proto.agent.trace.v1.CurrentLibraryConfig)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .opencensus.proto.agent.common.v1.Node node = 1;
  if (this->has_node()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *node_);
  }

  // .opencensus.proto.trace.v1.TraceConfig config = 2;
  if (this->has_config()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *config_);
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void CurrentLibraryConfig::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:opencensus.proto.agent.trace.v1.CurrentLibraryConfig)
  GOOGLE_DCHECK_NE(&from, this);
  const CurrentLibraryConfig* source =
      ::google::protobuf::DynamicCastToGenerated<CurrentLibraryConfig>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:opencensus.proto.agent.trace.v1.CurrentLibraryConfig)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:opencensus.proto.agent.trace.v1.CurrentLibraryConfig)
    MergeFrom(*source);
  }
}

void CurrentLibraryConfig::MergeFrom(const CurrentLibraryConfig& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:opencensus.proto.agent.trace.v1.CurrentLibraryConfig)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_node()) {
    mutable_node()->::opencensus::proto::agent::common::v1::Node::MergeFrom(from.node());
  }
  if (from.has_config()) {
    mutable_config()->::opencensus::proto::trace::v1::TraceConfig::MergeFrom(from.config());
  }
}

void CurrentLibraryConfig::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:opencensus.proto.agent.trace.v1.CurrentLibraryConfig)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CurrentLibraryConfig::CopyFrom(const CurrentLibraryConfig& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:opencensus.proto.agent.trace.v1.CurrentLibraryConfig)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CurrentLibraryConfig::IsInitialized() const {
  return true;
}

void CurrentLibraryConfig::Swap(CurrentLibraryConfig* other) {
  if (other == this) return;
  InternalSwap(other);
}
void CurrentLibraryConfig::InternalSwap(CurrentLibraryConfig* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(node_, other->node_);
  swap(config_, other->config_);
}

::google::protobuf::Metadata CurrentLibraryConfig::GetMetadata() const {
  ::google::protobuf::internal::AssignDescriptors(&::assign_descriptors_table_opencensus_2fproto_2fagent_2ftrace_2fv1_2ftrace_5fservice_2eproto);
  return ::file_level_metadata_opencensus_2fproto_2fagent_2ftrace_2fv1_2ftrace_5fservice_2eproto[kIndexInFileMessages];
}


// ===================================================================

void UpdatedLibraryConfig::InitAsDefaultInstance() {
  ::opencensus::proto::agent::trace::v1::_UpdatedLibraryConfig_default_instance_._instance.get_mutable()->node_ = const_cast< ::opencensus::proto::agent::common::v1::Node*>(
      ::opencensus::proto::agent::common::v1::Node::internal_default_instance());
  ::opencensus::proto::agent::trace::v1::_UpdatedLibraryConfig_default_instance_._instance.get_mutable()->config_ = const_cast< ::opencensus::proto::trace::v1::TraceConfig*>(
      ::opencensus::proto::trace::v1::TraceConfig::internal_default_instance());
}
class UpdatedLibraryConfig::HasBitSetters {
 public:
  static const ::opencensus::proto::agent::common::v1::Node& node(const UpdatedLibraryConfig* msg);
  static const ::opencensus::proto::trace::v1::TraceConfig& config(const UpdatedLibraryConfig* msg);
};

const ::opencensus::proto::agent::common::v1::Node&
UpdatedLibraryConfig::HasBitSetters::node(const UpdatedLibraryConfig* msg) {
  return *msg->node_;
}
const ::opencensus::proto::trace::v1::TraceConfig&
UpdatedLibraryConfig::HasBitSetters::config(const UpdatedLibraryConfig* msg) {
  return *msg->config_;
}
void UpdatedLibraryConfig::clear_node() {
  if (GetArenaNoVirtual() == nullptr && node_ != nullptr) {
    delete node_;
  }
  node_ = nullptr;
}
void UpdatedLibraryConfig::clear_config() {
  if (GetArenaNoVirtual() == nullptr && config_ != nullptr) {
    delete config_;
  }
  config_ = nullptr;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int UpdatedLibraryConfig::kNodeFieldNumber;
const int UpdatedLibraryConfig::kConfigFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

UpdatedLibraryConfig::UpdatedLibraryConfig()
  : ::google::protobuf::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:opencensus.proto.agent.trace.v1.UpdatedLibraryConfig)
}
UpdatedLibraryConfig::UpdatedLibraryConfig(const UpdatedLibraryConfig& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.has_node()) {
    node_ = new ::opencensus::proto::agent::common::v1::Node(*from.node_);
  } else {
    node_ = nullptr;
  }
  if (from.has_config()) {
    config_ = new ::opencensus::proto::trace::v1::TraceConfig(*from.config_);
  } else {
    config_ = nullptr;
  }
  // @@protoc_insertion_point(copy_constructor:opencensus.proto.agent.trace.v1.UpdatedLibraryConfig)
}

void UpdatedLibraryConfig::SharedCtor() {
  ::google::protobuf::internal::InitSCC(
      &scc_info_UpdatedLibraryConfig_opencensus_2fproto_2fagent_2ftrace_2fv1_2ftrace_5fservice_2eproto.base);
  ::memset(&node_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&config_) -
      reinterpret_cast<char*>(&node_)) + sizeof(config_));
}

UpdatedLibraryConfig::~UpdatedLibraryConfig() {
  // @@protoc_insertion_point(destructor:opencensus.proto.agent.trace.v1.UpdatedLibraryConfig)
  SharedDtor();
}

void UpdatedLibraryConfig::SharedDtor() {
  if (this != internal_default_instance()) delete node_;
  if (this != internal_default_instance()) delete config_;
}

void UpdatedLibraryConfig::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const UpdatedLibraryConfig& UpdatedLibraryConfig::default_instance() {
  ::google::protobuf::internal::InitSCC(&::scc_info_UpdatedLibraryConfig_opencensus_2fproto_2fagent_2ftrace_2fv1_2ftrace_5fservice_2eproto.base);
  return *internal_default_instance();
}


void UpdatedLibraryConfig::Clear() {
// @@protoc_insertion_point(message_clear_start:opencensus.proto.agent.trace.v1.UpdatedLibraryConfig)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaNoVirtual() == nullptr && node_ != nullptr) {
    delete node_;
  }
  node_ = nullptr;
  if (GetArenaNoVirtual() == nullptr && config_ != nullptr) {
    delete config_;
  }
  config_ = nullptr;
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* UpdatedLibraryConfig::_InternalParse(const char* begin, const char* end, void* object,
                  ::google::protobuf::internal::ParseContext* ctx) {
  auto msg = static_cast<UpdatedLibraryConfig*>(object);
  ::google::protobuf::int32 size; (void)size;
  int depth; (void)depth;
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::ParseFunc parser_till_end; (void)parser_till_end;
  auto ptr = begin;
  while (ptr < end) {
    ptr = ::google::protobuf::io::Parse32(ptr, &tag);
    GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
    switch (tag >> 3) {
      // .opencensus.proto.agent.common.v1.Node node = 1;
      case 1: {
        if (static_cast<::google::protobuf::uint8>(tag) != 10) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        parser_till_end = ::opencensus::proto::agent::common::v1::Node::_InternalParse;
        object = msg->mutable_node();
        if (size > end - ptr) goto len_delim_till_end;
        ptr += size;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ctx->ParseExactRange(
            {parser_till_end, object}, ptr - size, ptr));
        break;
      }
      // .opencensus.proto.trace.v1.TraceConfig config = 2;
      case 2: {
        if (static_cast<::google::protobuf::uint8>(tag) != 18) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        parser_till_end = ::opencensus::proto::trace::v1::TraceConfig::_InternalParse;
        object = msg->mutable_config();
        if (size > end - ptr) goto len_delim_till_end;
        ptr += size;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ctx->ParseExactRange(
            {parser_till_end, object}, ptr - size, ptr));
        break;
      }
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->EndGroup(tag);
          return ptr;
        }
        auto res = UnknownFieldParse(tag, {_InternalParse, msg},
          ptr, end, msg->_internal_metadata_.mutable_unknown_fields(), ctx);
        ptr = res.first;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr != nullptr);
        if (res.second) return ptr;
      }
    }  // switch
  }  // while
  return ptr;
len_delim_till_end:
  return ctx->StoreAndTailCall(ptr, end, {_InternalParse, msg},
                               {parser_till_end, object}, size);
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool UpdatedLibraryConfig::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:opencensus.proto.agent.trace.v1.UpdatedLibraryConfig)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .opencensus.proto.agent.common.v1.Node node = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (10 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_node()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .opencensus.proto.trace.v1.TraceConfig config = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (18 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_config()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:opencensus.proto.agent.trace.v1.UpdatedLibraryConfig)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:opencensus.proto.agent.trace.v1.UpdatedLibraryConfig)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void UpdatedLibraryConfig::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:opencensus.proto.agent.trace.v1.UpdatedLibraryConfig)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .opencensus.proto.agent.common.v1.Node node = 1;
  if (this->has_node()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, HasBitSetters::node(this), output);
  }

  // .opencensus.proto.trace.v1.TraceConfig config = 2;
  if (this->has_config()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, HasBitSetters::config(this), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:opencensus.proto.agent.trace.v1.UpdatedLibraryConfig)
}

::google::protobuf::uint8* UpdatedLibraryConfig::InternalSerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:opencensus.proto.agent.trace.v1.UpdatedLibraryConfig)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .opencensus.proto.agent.common.v1.Node node = 1;
  if (this->has_node()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, HasBitSetters::node(this), target);
  }

  // .opencensus.proto.trace.v1.TraceConfig config = 2;
  if (this->has_config()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        2, HasBitSetters::config(this), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:opencensus.proto.agent.trace.v1.UpdatedLibraryConfig)
  return target;
}

size_t UpdatedLibraryConfig::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:opencensus.proto.agent.trace.v1.UpdatedLibraryConfig)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .opencensus.proto.agent.common.v1.Node node = 1;
  if (this->has_node()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *node_);
  }

  // .opencensus.proto.trace.v1.TraceConfig config = 2;
  if (this->has_config()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *config_);
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void UpdatedLibraryConfig::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:opencensus.proto.agent.trace.v1.UpdatedLibraryConfig)
  GOOGLE_DCHECK_NE(&from, this);
  const UpdatedLibraryConfig* source =
      ::google::protobuf::DynamicCastToGenerated<UpdatedLibraryConfig>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:opencensus.proto.agent.trace.v1.UpdatedLibraryConfig)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:opencensus.proto.agent.trace.v1.UpdatedLibraryConfig)
    MergeFrom(*source);
  }
}

void UpdatedLibraryConfig::MergeFrom(const UpdatedLibraryConfig& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:opencensus.proto.agent.trace.v1.UpdatedLibraryConfig)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_node()) {
    mutable_node()->::opencensus::proto::agent::common::v1::Node::MergeFrom(from.node());
  }
  if (from.has_config()) {
    mutable_config()->::opencensus::proto::trace::v1::TraceConfig::MergeFrom(from.config());
  }
}

void UpdatedLibraryConfig::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:opencensus.proto.agent.trace.v1.UpdatedLibraryConfig)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void UpdatedLibraryConfig::CopyFrom(const UpdatedLibraryConfig& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:opencensus.proto.agent.trace.v1.UpdatedLibraryConfig)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool UpdatedLibraryConfig::IsInitialized() const {
  return true;
}

void UpdatedLibraryConfig::Swap(UpdatedLibraryConfig* other) {
  if (other == this) return;
  InternalSwap(other);
}
void UpdatedLibraryConfig::InternalSwap(UpdatedLibraryConfig* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(node_, other->node_);
  swap(config_, other->config_);
}

::google::protobuf::Metadata UpdatedLibraryConfig::GetMetadata() const {
  ::google::protobuf::internal::AssignDescriptors(&::assign_descriptors_table_opencensus_2fproto_2fagent_2ftrace_2fv1_2ftrace_5fservice_2eproto);
  return ::file_level_metadata_opencensus_2fproto_2fagent_2ftrace_2fv1_2ftrace_5fservice_2eproto[kIndexInFileMessages];
}


// ===================================================================

void ExportTraceServiceRequest::InitAsDefaultInstance() {
  ::opencensus::proto::agent::trace::v1::_ExportTraceServiceRequest_default_instance_._instance.get_mutable()->node_ = const_cast< ::opencensus::proto::agent::common::v1::Node*>(
      ::opencensus::proto::agent::common::v1::Node::internal_default_instance());
  ::opencensus::proto::agent::trace::v1::_ExportTraceServiceRequest_default_instance_._instance.get_mutable()->resource_ = const_cast< ::opencensus::proto::resource::v1::Resource*>(
      ::opencensus::proto::resource::v1::Resource::internal_default_instance());
}
class ExportTraceServiceRequest::HasBitSetters {
 public:
  static const ::opencensus::proto::agent::common::v1::Node& node(const ExportTraceServiceRequest* msg);
  static const ::opencensus::proto::resource::v1::Resource& resource(const ExportTraceServiceRequest* msg);
};

const ::opencensus::proto::agent::common::v1::Node&
ExportTraceServiceRequest::HasBitSetters::node(const ExportTraceServiceRequest* msg) {
  return *msg->node_;
}
const ::opencensus::proto::resource::v1::Resource&
ExportTraceServiceRequest::HasBitSetters::resource(const ExportTraceServiceRequest* msg) {
  return *msg->resource_;
}
void ExportTraceServiceRequest::clear_node() {
  if (GetArenaNoVirtual() == nullptr && node_ != nullptr) {
    delete node_;
  }
  node_ = nullptr;
}
void ExportTraceServiceRequest::clear_spans() {
  spans_.Clear();
}
void ExportTraceServiceRequest::clear_resource() {
  if (GetArenaNoVirtual() == nullptr && resource_ != nullptr) {
    delete resource_;
  }
  resource_ = nullptr;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ExportTraceServiceRequest::kNodeFieldNumber;
const int ExportTraceServiceRequest::kSpansFieldNumber;
const int ExportTraceServiceRequest::kResourceFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ExportTraceServiceRequest::ExportTraceServiceRequest()
  : ::google::protobuf::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:opencensus.proto.agent.trace.v1.ExportTraceServiceRequest)
}
ExportTraceServiceRequest::ExportTraceServiceRequest(const ExportTraceServiceRequest& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(nullptr),
      spans_(from.spans_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.has_node()) {
    node_ = new ::opencensus::proto::agent::common::v1::Node(*from.node_);
  } else {
    node_ = nullptr;
  }
  if (from.has_resource()) {
    resource_ = new ::opencensus::proto::resource::v1::Resource(*from.resource_);
  } else {
    resource_ = nullptr;
  }
  // @@protoc_insertion_point(copy_constructor:opencensus.proto.agent.trace.v1.ExportTraceServiceRequest)
}

void ExportTraceServiceRequest::SharedCtor() {
  ::google::protobuf::internal::InitSCC(
      &scc_info_ExportTraceServiceRequest_opencensus_2fproto_2fagent_2ftrace_2fv1_2ftrace_5fservice_2eproto.base);
  ::memset(&node_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&resource_) -
      reinterpret_cast<char*>(&node_)) + sizeof(resource_));
}

ExportTraceServiceRequest::~ExportTraceServiceRequest() {
  // @@protoc_insertion_point(destructor:opencensus.proto.agent.trace.v1.ExportTraceServiceRequest)
  SharedDtor();
}

void ExportTraceServiceRequest::SharedDtor() {
  if (this != internal_default_instance()) delete node_;
  if (this != internal_default_instance()) delete resource_;
}

void ExportTraceServiceRequest::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ExportTraceServiceRequest& ExportTraceServiceRequest::default_instance() {
  ::google::protobuf::internal::InitSCC(&::scc_info_ExportTraceServiceRequest_opencensus_2fproto_2fagent_2ftrace_2fv1_2ftrace_5fservice_2eproto.base);
  return *internal_default_instance();
}


void ExportTraceServiceRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:opencensus.proto.agent.trace.v1.ExportTraceServiceRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  spans_.Clear();
  if (GetArenaNoVirtual() == nullptr && node_ != nullptr) {
    delete node_;
  }
  node_ = nullptr;
  if (GetArenaNoVirtual() == nullptr && resource_ != nullptr) {
    delete resource_;
  }
  resource_ = nullptr;
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* ExportTraceServiceRequest::_InternalParse(const char* begin, const char* end, void* object,
                  ::google::protobuf::internal::ParseContext* ctx) {
  auto msg = static_cast<ExportTraceServiceRequest*>(object);
  ::google::protobuf::int32 size; (void)size;
  int depth; (void)depth;
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::ParseFunc parser_till_end; (void)parser_till_end;
  auto ptr = begin;
  while (ptr < end) {
    ptr = ::google::protobuf::io::Parse32(ptr, &tag);
    GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
    switch (tag >> 3) {
      // .opencensus.proto.agent.common.v1.Node node = 1;
      case 1: {
        if (static_cast<::google::protobuf::uint8>(tag) != 10) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        parser_till_end = ::opencensus::proto::agent::common::v1::Node::_InternalParse;
        object = msg->mutable_node();
        if (size > end - ptr) goto len_delim_till_end;
        ptr += size;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ctx->ParseExactRange(
            {parser_till_end, object}, ptr - size, ptr));
        break;
      }
      // repeated .opencensus.proto.trace.v1.Span spans = 2;
      case 2: {
        if (static_cast<::google::protobuf::uint8>(tag) != 18) goto handle_unusual;
        do {
          ptr = ::google::protobuf::io::ReadSize(ptr, &size);
          GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
          parser_till_end = ::opencensus::proto::trace::v1::Span::_InternalParse;
          object = msg->add_spans();
          if (size > end - ptr) goto len_delim_till_end;
          ptr += size;
          GOOGLE_PROTOBUF_PARSER_ASSERT(ctx->ParseExactRange(
              {parser_till_end, object}, ptr - size, ptr));
          if (ptr >= end) break;
        } while ((::google::protobuf::io::UnalignedLoad<::google::protobuf::uint64>(ptr) & 255) == 18 && (ptr += 1));
        break;
      }
      // .opencensus.proto.resource.v1.Resource resource = 3;
      case 3: {
        if (static_cast<::google::protobuf::uint8>(tag) != 26) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        parser_till_end = ::opencensus::proto::resource::v1::Resource::_InternalParse;
        object = msg->mutable_resource();
        if (size > end - ptr) goto len_delim_till_end;
        ptr += size;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ctx->ParseExactRange(
            {parser_till_end, object}, ptr - size, ptr));
        break;
      }
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->EndGroup(tag);
          return ptr;
        }
        auto res = UnknownFieldParse(tag, {_InternalParse, msg},
          ptr, end, msg->_internal_metadata_.mutable_unknown_fields(), ctx);
        ptr = res.first;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr != nullptr);
        if (res.second) return ptr;
      }
    }  // switch
  }  // while
  return ptr;
len_delim_till_end:
  return ctx->StoreAndTailCall(ptr, end, {_InternalParse, msg},
                               {parser_till_end, object}, size);
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool ExportTraceServiceRequest::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:opencensus.proto.agent.trace.v1.ExportTraceServiceRequest)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .opencensus.proto.agent.common.v1.Node node = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (10 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_node()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .opencensus.proto.trace.v1.Span spans = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (18 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_spans()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .opencensus.proto.resource.v1.Resource resource = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (26 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_resource()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:opencensus.proto.agent.trace.v1.ExportTraceServiceRequest)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:opencensus.proto.agent.trace.v1.ExportTraceServiceRequest)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void ExportTraceServiceRequest::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:opencensus.proto.agent.trace.v1.ExportTraceServiceRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .opencensus.proto.agent.common.v1.Node node = 1;
  if (this->has_node()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, HasBitSetters::node(this), output);
  }

  // repeated .opencensus.proto.trace.v1.Span spans = 2;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->spans_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2,
      this->spans(static_cast<int>(i)),
      output);
  }

  // .opencensus.proto.resource.v1.Resource resource = 3;
  if (this->has_resource()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, HasBitSetters::resource(this), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:opencensus.proto.agent.trace.v1.ExportTraceServiceRequest)
}

::google::protobuf::uint8* ExportTraceServiceRequest::InternalSerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:opencensus.proto.agent.trace.v1.ExportTraceServiceRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .opencensus.proto.agent.common.v1.Node node = 1;
  if (this->has_node()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, HasBitSetters::node(this), target);
  }

  // repeated .opencensus.proto.trace.v1.Span spans = 2;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->spans_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        2, this->spans(static_cast<int>(i)), target);
  }

  // .opencensus.proto.resource.v1.Resource resource = 3;
  if (this->has_resource()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        3, HasBitSetters::resource(this), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:opencensus.proto.agent.trace.v1.ExportTraceServiceRequest)
  return target;
}

size_t ExportTraceServiceRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:opencensus.proto.agent.trace.v1.ExportTraceServiceRequest)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .opencensus.proto.trace.v1.Span spans = 2;
  {
    unsigned int count = static_cast<unsigned int>(this->spans_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->spans(static_cast<int>(i)));
    }
  }

  // .opencensus.proto.agent.common.v1.Node node = 1;
  if (this->has_node()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *node_);
  }

  // .opencensus.proto.resource.v1.Resource resource = 3;
  if (this->has_resource()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *resource_);
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ExportTraceServiceRequest::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:opencensus.proto.agent.trace.v1.ExportTraceServiceRequest)
  GOOGLE_DCHECK_NE(&from, this);
  const ExportTraceServiceRequest* source =
      ::google::protobuf::DynamicCastToGenerated<ExportTraceServiceRequest>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:opencensus.proto.agent.trace.v1.ExportTraceServiceRequest)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:opencensus.proto.agent.trace.v1.ExportTraceServiceRequest)
    MergeFrom(*source);
  }
}

void ExportTraceServiceRequest::MergeFrom(const ExportTraceServiceRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:opencensus.proto.agent.trace.v1.ExportTraceServiceRequest)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  spans_.MergeFrom(from.spans_);
  if (from.has_node()) {
    mutable_node()->::opencensus::proto::agent::common::v1::Node::MergeFrom(from.node());
  }
  if (from.has_resource()) {
    mutable_resource()->::opencensus::proto::resource::v1::Resource::MergeFrom(from.resource());
  }
}

void ExportTraceServiceRequest::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:opencensus.proto.agent.trace.v1.ExportTraceServiceRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ExportTraceServiceRequest::CopyFrom(const ExportTraceServiceRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:opencensus.proto.agent.trace.v1.ExportTraceServiceRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ExportTraceServiceRequest::IsInitialized() const {
  return true;
}

void ExportTraceServiceRequest::Swap(ExportTraceServiceRequest* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ExportTraceServiceRequest::InternalSwap(ExportTraceServiceRequest* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  CastToBase(&spans_)->InternalSwap(CastToBase(&other->spans_));
  swap(node_, other->node_);
  swap(resource_, other->resource_);
}

::google::protobuf::Metadata ExportTraceServiceRequest::GetMetadata() const {
  ::google::protobuf::internal::AssignDescriptors(&::assign_descriptors_table_opencensus_2fproto_2fagent_2ftrace_2fv1_2ftrace_5fservice_2eproto);
  return ::file_level_metadata_opencensus_2fproto_2fagent_2ftrace_2fv1_2ftrace_5fservice_2eproto[kIndexInFileMessages];
}


// ===================================================================

void ExportTraceServiceResponse::InitAsDefaultInstance() {
}
class ExportTraceServiceResponse::HasBitSetters {
 public:
};

#if !defined(_MSC_VER) || _MSC_VER >= 1900
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ExportTraceServiceResponse::ExportTraceServiceResponse()
  : ::google::protobuf::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:opencensus.proto.agent.trace.v1.ExportTraceServiceResponse)
}
ExportTraceServiceResponse::ExportTraceServiceResponse(const ExportTraceServiceResponse& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:opencensus.proto.agent.trace.v1.ExportTraceServiceResponse)
}

void ExportTraceServiceResponse::SharedCtor() {
}

ExportTraceServiceResponse::~ExportTraceServiceResponse() {
  // @@protoc_insertion_point(destructor:opencensus.proto.agent.trace.v1.ExportTraceServiceResponse)
  SharedDtor();
}

void ExportTraceServiceResponse::SharedDtor() {
}

void ExportTraceServiceResponse::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ExportTraceServiceResponse& ExportTraceServiceResponse::default_instance() {
  ::google::protobuf::internal::InitSCC(&::scc_info_ExportTraceServiceResponse_opencensus_2fproto_2fagent_2ftrace_2fv1_2ftrace_5fservice_2eproto.base);
  return *internal_default_instance();
}


void ExportTraceServiceResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:opencensus.proto.agent.trace.v1.ExportTraceServiceResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* ExportTraceServiceResponse::_InternalParse(const char* begin, const char* end, void* object,
                  ::google::protobuf::internal::ParseContext* ctx) {
  auto msg = static_cast<ExportTraceServiceResponse*>(object);
  ::google::protobuf::int32 size; (void)size;
  int depth; (void)depth;
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::ParseFunc parser_till_end; (void)parser_till_end;
  auto ptr = begin;
  while (ptr < end) {
    ptr = ::google::protobuf::io::Parse32(ptr, &tag);
    GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
    switch (tag >> 3) {
      default: {
        if ((tag & 7) == 4 || tag == 0) {
          ctx->EndGroup(tag);
          return ptr;
        }
        auto res = UnknownFieldParse(tag, {_InternalParse, msg},
          ptr, end, msg->_internal_metadata_.mutable_unknown_fields(), ctx);
        ptr = res.first;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr != nullptr);
        if (res.second) return ptr;
      }
    }  // switch
  }  // while
  return ptr;
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool ExportTraceServiceResponse::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:opencensus.proto.agent.trace.v1.ExportTraceServiceResponse)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
  handle_unusual:
    if (tag == 0) {
      goto success;
    }
    DO_(::google::protobuf::internal::WireFormat::SkipField(
          input, tag, _internal_metadata_.mutable_unknown_fields()));
  }
success:
  // @@protoc_insertion_point(parse_success:opencensus.proto.agent.trace.v1.ExportTraceServiceResponse)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:opencensus.proto.agent.trace.v1.ExportTraceServiceResponse)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void ExportTraceServiceResponse::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:opencensus.proto.agent.trace.v1.ExportTraceServiceResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:opencensus.proto.agent.trace.v1.ExportTraceServiceResponse)
}

::google::protobuf::uint8* ExportTraceServiceResponse::InternalSerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:opencensus.proto.agent.trace.v1.ExportTraceServiceResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:opencensus.proto.agent.trace.v1.ExportTraceServiceResponse)
  return target;
}

size_t ExportTraceServiceResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:opencensus.proto.agent.trace.v1.ExportTraceServiceResponse)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ExportTraceServiceResponse::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:opencensus.proto.agent.trace.v1.ExportTraceServiceResponse)
  GOOGLE_DCHECK_NE(&from, this);
  const ExportTraceServiceResponse* source =
      ::google::protobuf::DynamicCastToGenerated<ExportTraceServiceResponse>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:opencensus.proto.agent.trace.v1.ExportTraceServiceResponse)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:opencensus.proto.agent.trace.v1.ExportTraceServiceResponse)
    MergeFrom(*source);
  }
}

void ExportTraceServiceResponse::MergeFrom(const ExportTraceServiceResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:opencensus.proto.agent.trace.v1.ExportTraceServiceResponse)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

}

void ExportTraceServiceResponse::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:opencensus.proto.agent.trace.v1.ExportTraceServiceResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ExportTraceServiceResponse::CopyFrom(const ExportTraceServiceResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:opencensus.proto.agent.trace.v1.ExportTraceServiceResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ExportTraceServiceResponse::IsInitialized() const {
  return true;
}

void ExportTraceServiceResponse::Swap(ExportTraceServiceResponse* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ExportTraceServiceResponse::InternalSwap(ExportTraceServiceResponse* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata ExportTraceServiceResponse::GetMetadata() const {
  ::google::protobuf::internal::AssignDescriptors(&::assign_descriptors_table_opencensus_2fproto_2fagent_2ftrace_2fv1_2ftrace_5fservice_2eproto);
  return ::file_level_metadata_opencensus_2fproto_2fagent_2ftrace_2fv1_2ftrace_5fservice_2eproto[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace v1
}  // namespace trace
}  // namespace agent
}  // namespace proto
}  // namespace opencensus
namespace google {
namespace protobuf {
template<> PROTOBUF_NOINLINE ::opencensus::proto::agent::trace::v1::CurrentLibraryConfig* Arena::CreateMaybeMessage< ::opencensus::proto::agent::trace::v1::CurrentLibraryConfig >(Arena* arena) {
  return Arena::CreateInternal< ::opencensus::proto::agent::trace::v1::CurrentLibraryConfig >(arena);
}
template<> PROTOBUF_NOINLINE ::opencensus::proto::agent::trace::v1::UpdatedLibraryConfig* Arena::CreateMaybeMessage< ::opencensus::proto::agent::trace::v1::UpdatedLibraryConfig >(Arena* arena) {
  return Arena::CreateInternal< ::opencensus::proto::agent::trace::v1::UpdatedLibraryConfig >(arena);
}
template<> PROTOBUF_NOINLINE ::opencensus::proto::agent::trace::v1::ExportTraceServiceRequest* Arena::CreateMaybeMessage< ::opencensus::proto::agent::trace::v1::ExportTraceServiceRequest >(Arena* arena) {
  return Arena::CreateInternal< ::opencensus::proto::agent::trace::v1::ExportTraceServiceRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::opencensus::proto::agent::trace::v1::ExportTraceServiceResponse* Arena::CreateMaybeMessage< ::opencensus::proto::agent::trace::v1::ExportTraceServiceResponse >(Arena* arena) {
  return Arena::CreateInternal< ::opencensus::proto::agent::trace::v1::ExportTraceServiceResponse >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
