AllCops:
  TargetRubyVersion: '2.4.0'

Layout/LineLength:
  Enabled: false
Metrics/ParameterLists:
  Enabled: false
Metrics/ClassLength:
  Max: 110
Metrics/MethodLength:
  Max: 20
Style/ModuleFunction:
  Enabled: false
Lint/UnusedMethodArgument:
  Enabled: false
